#!/usr/bin/env bash
# ==============================================================================
# apply-my-settings.en.sh (English Version)
# Automated restoration script for personalized macOS settings.
# Auto-generated by scripts/export-macos-settings.en.sh
# ==============================================================================

echo "🚀 Applying personalized macOS settings..."

# Close System Settings if open to prevent configuration overwrites
osascript -e 'tell application "System Settings" to quit' 2>/dev/null || true
osascript -e 'tell application "System Preferences" to quit' 2>/dev/null || true

echo "⚙️  Configuring: Keyboard & Key Repeat Rates..."
defaults write -g "InitialKeyRepeat" -int 15
defaults write -g "KeyRepeat" -float 2
defaults write -g "ApplePressAndHoldEnabled" -bool false
defaults write -g "NSAutomaticSpellingCorrectionEnabled" -bool false
defaults write -g "NSAutomaticCapitalizationEnabled" -bool false
defaults write -g "NSAutomaticPeriodSubstitutionEnabled" -bool false

echo "⚙️  Configuring: Trackpad Gestures & Touch..."
defaults write com.apple.AppleMultitouchTrackpad "Clicking" -bool true
defaults write com.apple.AppleMultitouchTrackpad "TrackpadThreeFingerDrag" -bool true
defaults write com.apple.AppleMultitouchTrackpad "TrackpadRightClick" -bool true
defaults write com.apple.AppleMultitouchTrackpad "TrackpadCornerSecondaryClick" -int 0
defaults write com.apple.AppleMultitouchTrackpad "TrackpadScroll" -bool true
defaults write com.apple.AppleMultitouchTrackpad "TrackpadPinch" -int 1
defaults write com.apple.AppleMultitouchTrackpad "TrackpadRotate" -int 1
defaults write com.apple.AppleMultitouchTrackpad "TrackpadTwoFingerDoubleTapGesture" -int 1
defaults write com.apple.AppleMultitouchTrackpad "TrackpadThreeFingerTapGesture" -int 0
defaults write com.apple.AppleMultitouchTrackpad "TrackpadThreeFingerHorizSwipeGesture" -int 0
defaults write com.apple.AppleMultitouchTrackpad "TrackpadThreeFingerVertSwipeGesture" -int 0
defaults write com.apple.AppleMultitouchTrackpad "TrackpadFourFingerHorizSwipeGesture" -int 2
defaults write com.apple.AppleMultitouchTrackpad "TrackpadFourFingerVertSwipeGesture" -int 2
defaults write com.apple.AppleMultitouchTrackpad "TrackpadFourFingerPinchGesture" -int 2
defaults write com.apple.AppleMultitouchTrackpad "TrackpadFiveFingerPinchGesture" -int 2

echo "⚙️  Configuring: Bluetooth Trackpad Gestures..."
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad "Clicking" -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad "TrackpadThreeFingerDrag" -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad "TrackpadRightClick" -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad "TrackpadCornerSecondaryClick" -int 0
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad "TrackpadFourFingerHorizSwipeGesture" -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad "TrackpadFourFingerVertSwipeGesture" -int 2

echo "⚙️  Configuring: Mouse & Trackpad Speed..."
defaults write -g "com.apple.trackpad.scaling" -float 3
defaults write -g "com.apple.mouse.scaling" -float 3
defaults write -g "com.apple.scrollwheel.scaling" -float 1

echo "⚙️  Configuring: Finder Preferences..."
defaults write com.apple.finder "ShowPathbar" -bool true
defaults write com.apple.finder "ShowStatusBar" -bool true
defaults write com.apple.finder "_FXSortFoldersFirst" -bool true

echo "⚙️  Configuring: File Extensions Visibility..."
defaults write NSGlobalDomain "AppleShowAllExtensions" -bool true

echo "⚙️  Configuring: Dock & Mission Control..."
defaults write com.apple.dock "autohide" -bool false
defaults write com.apple.dock "tilesize" -float 36
defaults write com.apple.dock "largesize" -float 37
defaults write com.apple.dock "show-recents" -bool false

# Restart background processes to apply preferences
echo "🔄 Restarting Finder, Dock, and SystemUIServer..."
killall Finder 2>/dev/null || true
killall Dock 2>/dev/null || true
killall SystemUIServer 2>/dev/null || true

echo "✅ Done! All your personal macOS settings have been successfully restored."
