#!/usr/bin/env bash
# ==============================================================================
# scripts/export-macos-settings.en.sh (English Version)
# Automatically extracts current macOS system settings (Trackpad, Keyboard, Finder, Dock...)
# and generates `backups/apply-my-settings.en.sh` for easy restoration on any new Mac.
# ==============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BACKUP_DIR="$PROJECT_ROOT/backups"

mkdir -p "$BACKUP_DIR"
OUTPUT_FILE="$BACKUP_DIR/apply-my-settings.en.sh"

echo "🔍 Reading current system preferences from your Mac..."

cat << 'EOF' > "$OUTPUT_FILE"
#!/usr/bin/env bash
# ==============================================================================
# apply-my-settings.en.sh (English Version)
# Automated restoration script for personalized macOS settings.
# Auto-generated by scripts/export-macos-settings.en.sh
# ==============================================================================

echo "🚀 Applying personalized macOS settings..."

# Close System Settings if open to prevent configuration overwrites
osascript -e 'tell application "System Settings" to quit' 2>/dev/null || true
osascript -e 'tell application "System Preferences" to quit' 2>/dev/null || true

EOF

# Safe defaults read/write exporter helper function
export_domain_keys() {
    local domain="$1"
    local title="$2"
    shift 2
    local keys=("$@")

    echo "echo \"⚙️  Configuring: $title...\"" >> "$OUTPUT_FILE"
    for key in "${keys[@]}"; do
        if val=$(defaults read "$domain" "$key" 2>/dev/null); then
            type=$(defaults read-type "$domain" "$key" 2>/dev/null | awk '{print $NF}' || echo "string")
            case "$type" in
                boolean)
                    if [ "$val" = "1" ] || [ "$val" = "true" ]; then
                        echo "defaults write $domain \"$key\" -bool true" >> "$OUTPUT_FILE"
                    else
                        echo "defaults write $domain \"$key\" -bool false" >> "$OUTPUT_FILE"
                    fi
                    ;;
                integer)
                    echo "defaults write $domain \"$key\" -int $val" >> "$OUTPUT_FILE"
                    ;;
                float)
                    echo "defaults write $domain \"$key\" -float $val" >> "$OUTPUT_FILE"
                    ;;
                string)
                    echo "defaults write $domain \"$key\" -string \"$val\"" >> "$OUTPUT_FILE"
                    ;;
                *)
                    ;;
            esac
        fi
    done
    echo "" >> "$OUTPUT_FILE"
}

# 1. Keyboard & Key Repeat
export_domain_keys "-g" "Keyboard & Key Repeat Rates" \
    "InitialKeyRepeat" \
    "KeyRepeat" \
    "ApplePressAndHoldEnabled" \
    "NSAutomaticSpellingCorrectionEnabled" \
    "NSAutomaticCapitalizationEnabled" \
    "NSAutomaticPeriodSubstitutionEnabled"

# 2. Trackpad Gestures & Touch
export_domain_keys "com.apple.AppleMultitouchTrackpad" "Trackpad Gestures & Touch" \
    "Clicking" \
    "TrackpadThreeFingerDrag" \
    "TrackpadRightClick" \
    "TrackpadCornerSecondaryClick" \
    "TrackpadScroll" \
    "TrackpadPinch" \
    "TrackpadRotate" \
    "TrackpadTwoFingerDoubleTapGesture" \
    "TrackpadThreeFingerTapGesture" \
    "TrackpadThreeFingerHorizSwipeGesture" \
    "TrackpadThreeFingerVertSwipeGesture" \
    "TrackpadFourFingerHorizSwipeGesture" \
    "TrackpadFourFingerVertSwipeGesture" \
    "TrackpadFourFingerPinchGesture" \
    "TrackpadFiveFingerPinchGesture"

export_domain_keys "com.apple.driver.AppleBluetoothMultitouch.trackpad" "Bluetooth Trackpad Gestures" \
    "Clicking" \
    "TrackpadThreeFingerDrag" \
    "TrackpadRightClick" \
    "TrackpadCornerSecondaryClick" \
    "TrackpadFourFingerHorizSwipeGesture" \
    "TrackpadFourFingerVertSwipeGesture"

# 3. Mouse & Trackpad Scaling (Tracking Speed)
export_domain_keys "-g" "Mouse & Trackpad Speed" \
    "com.apple.trackpad.scaling" \
    "com.apple.mouse.scaling" \
    "com.apple.scrollwheel.scaling"

# 4. Finder & File Display
export_domain_keys "com.apple.finder" "Finder Preferences" \
    "ShowPathbar" \
    "ShowStatusBar" \
    "_FXSortFoldersFirst" \
    "FXDefaultSearchScope" \
    "FXEnableExtensionChangeWarning" \
    "AppleShowAllFiles"

export_domain_keys "NSGlobalDomain" "File Extensions Visibility" \
    "AppleShowAllExtensions"

# 5. Dock & Mission Control
export_domain_keys "com.apple.dock" "Dock & Mission Control" \
    "autohide" \
    "autohide-delay" \
    "autohide-time-modifier" \
    "tilesize" \
    "magnification" \
    "largesize" \
    "show-recents" \
    "mru-spaces"

# Restart affected background processes to apply changes immediately
cat << 'EOF' >> "$OUTPUT_FILE"
# Restart background processes to apply preferences
echo "🔄 Restarting Finder, Dock, and SystemUIServer..."
killall Finder 2>/dev/null || true
killall Dock 2>/dev/null || true
killall SystemUIServer 2>/dev/null || true

echo "✅ Done! All your personal macOS settings have been successfully restored."
EOF

chmod +x "$OUTPUT_FILE"

echo "========================================================================"
echo "✅ CONFIGURATION FILE EXPORTED SUCCESSFULLY!"
echo "📁 File Location: backups/apply-my-settings.en.sh"
echo "👉 How to restore on any new Mac: Simply run:"
echo "   bash backups/apply-my-settings.en.sh"
echo "========================================================================"
